rem python 02_insertDailyRatiosToMySQLDB.py 1140602 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250602.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140603 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250603.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140604 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250604.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140605 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250605.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140606 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250606.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140609 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250609.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140610 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250610.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140611 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250611.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140612 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250612.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140613 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250613.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140616 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250616.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140617 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250617.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140618 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250618.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140619 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250619.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140620 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250620.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140623 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250623.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140624 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250624.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140625 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250625.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140626 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250626.txt
rem python 02_insertDailyRatiosToMySQLDB.py 1140627 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250627.txt

python 02_insertDailyRatiosToMySQLDB.py 1140630 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250630.txt
python 02_insertDailyRatiosToMySQLDB.py 1140701 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250701.txt
python 02_insertDailyRatiosToMySQLDB.py 1140702 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250702.txt
python 02_insertDailyRatiosToMySQLDB.py 1140703 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250703.txt
python 02_insertDailyRatiosToMySQLDB.py 1140704 stocks_らセ痲ゑ崔瞯の基瞓ゑ-20250704.txt
