Python FormatFile.py 0050元大台灣50日線-20220717.csv 0050.txt
Python InsertStocksFromPolarisToMySQLDB.py 0050 0050.txt
Python GetFileFromDBv2.py 0050
transFile2datv2.exe 0050

Python FormatFile.py 0056元大高股息日線-20220717.csv 0056.txt
Python InsertStocksFromPolarisToMySQLDB.py 0056 0056.txt
Python GetFileFromDBv2.py 0056
transFile2datv2.exe 0056

Python FormatFile.py 00878國泰永續高股息日線-20220717.csv 00878.txt
Python InsertStocksFromPolarisToMySQLDB.py 00878 00878.txt
Python GetFileFromDBv2.py 00878
transFile2datv2.exe 00878

Python FormatFile.py 1101台泥日線-20220717.csv 1101.txt
Python InsertStocksFromPolarisToMySQLDB.py 1101 1101.txt
Python GetFileFromDBv2.py 1101
transFile2datv2.exe 1101

Python FormatFile.py 1102亞泥日線-20220717.csv 1102.txt
Python InsertStocksFromPolarisToMySQLDB.py 1102 1102.txt
Python GetFileFromDBv2.py 1102
transFile2datv2.exe 1102

Python FormatFile.py 1210大成日線-20220717.csv 1210.txt
Python InsertStocksFromPolarisToMySQLDB.py 1210 1210.txt
Python GetFileFromDBv2.py 1210
transFile2datv2.exe 1210

Python FormatFile.py 1215卜蜂日線-20220717.csv 1215.txt
Python InsertStocksFromPolarisToMySQLDB.py 1215 1215.txt
Python GetFileFromDBv2.py 1215
transFile2datv2.exe 1215

Python FormatFile.py 1301台塑日線-20220717.csv 1301.txt
Python InsertStocksFromPolarisToMySQLDB.py 1301 1301.txt
Python GetFileFromDBv2.py 1301
transFile2datv2.exe 1301

Python FormatFile.py 1303南亞日線-20220717.csv 1303.txt
Python InsertStocksFromPolarisToMySQLDB.py 1303 1303.txt
Python GetFileFromDBv2.py 1303
transFile2datv2.exe 1303

Python FormatFile.py 1326台化日線-20220717.csv 1326.txt
Python InsertStocksFromPolarisToMySQLDB.py 1326 1326.txt
Python GetFileFromDBv2.py 1326
transFile2datv2.exe 1326

Python FormatFile.py 1476儒鴻日線-20220717.csv 1476.txt
Python InsertStocksFromPolarisToMySQLDB.py 1476 1476.txt
Python GetFileFromDBv2.py 1476
transFile2datv2.exe 1476

Python FormatFile.py 1513中興電日線-20220717.csv 1513.txt
Python InsertStocksFromPolarisToMySQLDB.py 1513 1513.txt
Python GetFileFromDBv2.py 1513
transFile2datv2.exe 1513

Python FormatFile.py 1536和大日線-20220717.csv 1536.txt
Python InsertStocksFromPolarisToMySQLDB.py 1536 1536.txt
Python GetFileFromDBv2.py 1536
transFile2datv2.exe 1536

Python FormatFile.py 1558伸興日線-20220717.csv 1558.txt
Python InsertStocksFromPolarisToMySQLDB.py 1558 1558.txt
Python GetFileFromDBv2.py 1558
transFile2datv2.exe 1558

Python FormatFile.py 2002中鋼日線-20220717.csv 2002.txt
Python InsertStocksFromPolarisToMySQLDB.py 2002 2002.txt
Python GetFileFromDBv2.py 2002
transFile2datv2.exe 2002

Python FormatFile.py 2049上銀日線-20220717.csv 2049.txt
Python InsertStocksFromPolarisToMySQLDB.py 2049 2049.txt
Python GetFileFromDBv2.py 2049
transFile2datv2.exe 2049

Python FormatFile.py 2312金寶日線-20220717.csv 2312.txt
Python InsertStocksFromPolarisToMySQLDB.py 2312 2312.txt
Python GetFileFromDBv2.py 2312
transFile2datv2.exe 2312

Python FormatFile.py 2324仁寶日線-20220717.csv 2324.txt
Python InsertStocksFromPolarisToMySQLDB.py 2324 2324.txt
Python GetFileFromDBv2.py 2324
transFile2datv2.exe 2324

Python FormatFile.py 2412中華電日線-20220717.csv 2412.txt
Python InsertStocksFromPolarisToMySQLDB.py 2412 2412.txt
Python GetFileFromDBv2.py 2412
transFile2datv2.exe 2412

Python FormatFile.py 3045台灣大日線-20220717.csv 3045.txt
Python InsertStocksFromPolarisToMySQLDB.py 3045 3045.txt
Python GetFileFromDBv2.py 3045
transFile2datv2.exe 3045

Python FormatFile.py 3491昇達科日線-20220717.csv 3491.txt
Python InsertStocksFromPolarisToMySQLDB.py 3491 3491.txt
Python GetFileFromDBv2.py 3491
transFile2datv2.exe 3491

Python FormatFile.py 3546宇峻日線-20220717.csv 3546.txt
Python InsertStocksFromPolarisToMySQLDB.py 3546 3546.txt
Python GetFileFromDBv2.py 3546
transFile2datv2.exe 3546

Python FormatFile.py 3576聯合再生日線-20220717.csv 3576.txt
Python InsertStocksFromPolarisToMySQLDB.py 3576 3576.txt
Python GetFileFromDBv2.py 3576
transFile2datv2.exe 3576

Python FormatFile.py 3714富采日線-20220717.csv 3714.txt
Python InsertStocksFromPolarisToMySQLDB.py 3714 3714.txt
Python GetFileFromDBv2.py 3714
transFile2datv2.exe 3714

Python FormatFile.py 4763材料-KY日線-20220717.csv 4763.txt
Python InsertStocksFromPolarisToMySQLDB.py 4763 4763.txt
Python GetFileFromDBv2.py 4763
transFile2datv2.exe 4763

Python FormatFile.py 5388中磊日線-20220717.csv 5388.txt
Python InsertStocksFromPolarisToMySQLDB.py 5388 5388.txt
Python GetFileFromDBv2.py 5388
transFile2datv2.exe 5388

Python FormatFile.py 6443元晶日線-20220717.csv 6443.txt
Python InsertStocksFromPolarisToMySQLDB.py 6443 6443.txt
Python GetFileFromDBv2.py 6443
transFile2datv2.exe 6443

Python FormatFile.py 6505台塑化日線-20220717.csv 6505.txt
Python InsertStocksFromPolarisToMySQLDB.py 6505 6505.txt
Python GetFileFromDBv2.py 6505
transFile2datv2.exe 6505

Python FormatFile.py 6706惠特日線-20220717.csv 6706.txt
Python InsertStocksFromPolarisToMySQLDB.py 6706 6706.txt
Python GetFileFromDBv2.py 6706
transFile2datv2.exe 6706

Python FormatFile.py 6803崑鼎日線-20220717.csv 6803.txt
Python InsertStocksFromPolarisToMySQLDB.py 6803 6803.txt
Python GetFileFromDBv2.py 6803
transFile2datv2.exe 6803

Python FormatFile.py 8341日友日線-20220717.csv 8341.txt
Python InsertStocksFromPolarisToMySQLDB.py 8341 8341.txt
Python GetFileFromDBv2.py 8341
transFile2datv2.exe 8341

Python FormatFile.py 8422可寧衛日線-20220717.csv 8422.txt
Python InsertStocksFromPolarisToMySQLDB.py 8422 8422.txt
Python GetFileFromDBv2.py 8422
transFile2datv2.exe 8422

Python FormatFile.py 8436大江日線-20220717.csv 8436.txt
Python InsertStocksFromPolarisToMySQLDB.py 8436 8436.txt
Python GetFileFromDBv2.py 8436
transFile2datv2.exe 8436

Python FormatFile.py 8489三貝德日線-20220717.csv 8489.txt
Python InsertStocksFromPolarisToMySQLDB.py 8489 8489.txt
Python GetFileFromDBv2.py 8489
transFile2datv2.exe 8489

Python FormatFile.py 9958世紀鋼日線-20220717.csv 9958.txt
Python InsertStocksFromPolarisToMySQLDB.py 9958 9958.txt
Python GetFileFromDBv2.py 9958
transFile2datv2.exe 9958

