python 01_getStocksDailyRatiosData.py 20051201
python 01_formatStocksDailyRatiosData.py 20051201
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051202
python 01_formatStocksDailyRatiosData.py 20051202
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051203
python 01_formatStocksDailyRatiosData.py 20051203
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051204
python 01_formatStocksDailyRatiosData.py 20051204
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051205
python 01_formatStocksDailyRatiosData.py 20051205
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051206
python 01_formatStocksDailyRatiosData.py 20051206
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051207
python 01_formatStocksDailyRatiosData.py 20051207
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051208
python 01_formatStocksDailyRatiosData.py 20051208
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051209
python 01_formatStocksDailyRatiosData.py 20051209
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051210
python 01_formatStocksDailyRatiosData.py 20051210
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051211
python 01_formatStocksDailyRatiosData.py 20051211
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051212
python 01_formatStocksDailyRatiosData.py 20051212
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051213
python 01_formatStocksDailyRatiosData.py 20051213
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051214
python 01_formatStocksDailyRatiosData.py 20051214
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051215
python 01_formatStocksDailyRatiosData.py 20051215
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051216
python 01_formatStocksDailyRatiosData.py 20051216
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051217
python 01_formatStocksDailyRatiosData.py 20051217
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051218
python 01_formatStocksDailyRatiosData.py 20051218
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051219
python 01_formatStocksDailyRatiosData.py 20051219
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051220
python 01_formatStocksDailyRatiosData.py 20051220
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051221
python 01_formatStocksDailyRatiosData.py 20051221
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051222
python 01_formatStocksDailyRatiosData.py 20051222
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051223
python 01_formatStocksDailyRatiosData.py 20051223
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051224
python 01_formatStocksDailyRatiosData.py 20051224
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051225
python 01_formatStocksDailyRatiosData.py 20051225
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051226
python 01_formatStocksDailyRatiosData.py 20051226
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051227
python 01_formatStocksDailyRatiosData.py 20051227
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051228
python 01_formatStocksDailyRatiosData.py 20051228
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051229
python 01_formatStocksDailyRatiosData.py 20051229
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051230
python 01_formatStocksDailyRatiosData.py 20051230
timeout /t 10
rem wait 10 sec.
python 01_getStocksDailyRatiosData.py 20051231
python 01_formatStocksDailyRatiosData.py 20051231
timeout /t 10
rem wait 10 sec.
